### ISSUE TITLE
No response when sending out transaction

### ISSUE THREAD

**Issue by rlinxy** [alephium/alephium#1032]
The wallet doesn't reply when we send out payment to the address 1dNFdSzV2pVUQ9mmY6eTNoZyhwQWcDEJGE7rzvgiGQva.
The wallet is working fine for sending out transations to other addresses, but just the above address, we always got problem when sending out to it.
<img width="1091" alt="04b6c0ce7836671e41a7636ab0a3267" src="https://github.com/alephium/alephium/assets/39939703/253241eb-102e-4303-9b3e-46eb93643c0c">

Please advise, thanks

**Comment by rlinxy** [comment]
Tried several times, seems it's not caused by some specific wallet address. 
No idea what's wrong is it.
I will wait for more confirms before send out the next transaction, hope it works.

**Comment by rlinxy** [comment]
Doesn't work, sometimes still get no response after 'wallet transafer'.
Don't have a clue yet, the node version is 2.8.1

**Comment by polarker** [comment]
@rlinxy Is it related to this: https://docs.alephium.org/mining/solo-mining-guide/#security

You might want to configure `alephium.api.network-interface` and apikey like https://github.com/alephium/alephium-stack/blob/master/mainnet/user.conf#L1

**Comment by rlinxy** [comment]
No, I am op from 666pool, actually our pool can send out most of the payment successfully without problem, but sometimes the wallet/node just doesn't reply correctly after we call 'wallet transfer'. Just got empty reply and timeout, the transaction could not be sent. Don't have a clue.

**Comment by rlinxy** [comment]
So it's not an issue related to the API key

**Comment by tdroxler** [comment]
[CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) errors are painful, if you access your node's swagger remotely, CORS might hit you. If you ssh to your node and make the curl command directly there it should work.

When you say: sometimes the wallet-node just doesn't reply.

Are you always calling from the same place, the same way?

**Comment by rlinxy** [comment]
Yes, we access the node RPC API locally, to be more specific, the ALPH node and the mining pool are running on the same ECS. 
It has been working fine before Feb 8th, just don't know what's wrong, sometimes the wallet didn't give correct reply recently as I mentioned above

**Comment by rlinxy** [comment]
> @rlinxy Did see any logs in `alephium.log` and `alephium-errors.log`?

No, I just checked the logs, there is no relative log. 
It just happened again at 10:23AM UTC+8 today, and the latest log for  alephium-errors.log is at 16:56:25pm yesterday.
alephium.log is empty.
BTW, the node is working fine, cuz we are keeping mining blocks.

**Comment by rlinxy** [comment]
After several days testing, I guess it was caused by 'not enough balance', just don't know why we didn't get an error message for this. Closed for now, thanks.
