### ISSUE TITLE
Misbehavior: InvalidFlowData / Invalid Block/header

### ISSUE THREAD

**Issue by Stas724** [alephium/alephium#1136]
![Solo-Node](https://github.com/alephium/alephium/assets/92892178/bf399802-963b-47b4-bfd0-cd48ad581a22)

At this moment of time this has been a on-going issue for nearly 2 months for me. pretty much every single week i have to reinstall windows and redownload fresh mainnet blocks just to get it to work. What the heck is going on? 

system specs:

Windows 11 23h2 HOME x64

Core i9 14900k

64GB DDR5

Z790 gaming-e Wi-Fi II Motherboard

Samsung 990 PRO 2TB NVME

this is strictly just a server node.

i have over 30 GPUs I'm trying to mine with on this node and there is zero stability. I have tried to-do this on different system with different specs on different versions of windows and i am just getting the same similar result. I am very confident at this stage that i have exhausted every single option i know of and i am very confident that this isn't a user error related issue. I have attached a SS of what i am referring to.  Thanks!

**Comment by polarker** [comment]
Hey @Stas724, this is usually because the system time of OS is out of sync. Could you please resync?

It had happened to a few community members in the past.

**Comment by Stas724** [comment]
> Hey @Stas724, this is usually because the system time of OS is out of sync. Could you please resync?
> 
> It had happened to a few community members in the past.

@polarker I can confirm that this has resolved my issue! Thank you; i would have not even thought about the time sync. even though it was on the right hour. seemed like a few seconds off would cause this issue! thanks again! #closed #resolved
