### ISSUE TITLE
List wallets should always list the wallets, even when locked

### ISSUE THREAD

**Issue by killerwhile** [alephium/alephium#128]
# Issue type
bug

# Affected version
v0.7.1

# Description
The list wallets API call returns 401 when at least one wallet is locked.
Since the response contains a lock flag, it should always list all the wallets.

# How to reproduce
Create two wallets, wait until they are locked, unlock one, call list wallet function. It returns 401.
Unlock the second one, it returns the correct list of wallet.

**Comment by tdroxler** [comment]
Thx for the catch and the great bug report :+1:
