### ISSUE TITLE
Add a `reason` field in error responses

### ISSUE THREAD

**Issue by killerwhile** [alephium/alephium#130]
# Issue type
improvement

# Affected version
v0.7.1

# Description
The error response are rather rough, they especially do not return any meaningful reason of the error (except a "server error").
It would be good for the caller to get more details about the error.

**Comment by tdroxler** [comment]
@killerwhile https://github.com/alephium/alephium/pull/164 should resolves this issue, the errors' message might still be sometime not very precise, but we'll improve step by step.
