### ISSUE TITLE
Discrepency in wiki between testnet and explorer UrI (devnet.alephium.org)

### ISSUE THREAD

**Issue by killerwhile** [alephium/alephium#131]
# Issue type
improvement

# Affected version
v0.7.1

# Description
The wiki advises us to point our node to testnet, while the block explorer is http://devnet.alephium.org.
It's misleading to know if I'll be able to see my TX in the block explorer -- names should match.

**Comment by polarker** [comment]
Now [https://testnet.alephium.org](https://testnet.alephium.org) is on service, and the wiki is updated as well. I am closing this. @killerwhile Thanks again for reporting this!

**Comment by killerwhile** [comment]
Really cool, thanks!
