### ISSUE TITLE
Add a --help parameter in the jar to list available options

### ISSUE THREAD

**Issue by killerwhile** [alephium/alephium#132]
# Issue type
improvement

# Affected version
v0.7.1

# Description
Not all sysadmins are familiar with hocon format, nor are wanting to unzip config files from the jar to get the list of available parameters and their defaults.

An improvement would be to add a `--help` parameter (or `--dump-config`) which details the configuration parameters and the current value.

**Comment by polarker** [comment]
@killerwhile I totally agree with your argument that unzipping config files from the jar is not user&dev-friendly. Therefore, we dump all the configs under `~/.alephium` already in three files: `user.conf`, `network.conf`, `system.conf`. The first ones will overwrite the later ones.

How do you feel about our approach?

**Comment by polarker** [comment]
We also log the current config in `~/.alephium/logs/alephium-debug.log`, like this:
```
2021-03-22 17:05:53,567 [main]          DEBUG o.a.app.BootUp                         - akka {
    actor {
        default-dispatcher {
            executor=fork-join-executor
            fork-join-executor {
                parallelism-factor=0.5
            }
            throughput=1
        }
        ...
    }
  }
  alephium {
    ...
    ...
  }
```

**Comment by killerwhile** [comment]
Your dump of the config is good ✅.

Regarding the parameters, what I'm actually missing is their meaning.
Example: what `alephium.broker.groups` means? What values could I put in?
I know some docs will follow, but doc will become obsolete and having a programmatic way of generating such list is interesting on the long run.

A typical example I have in mind is:
```
docker run -it --rm gcr.io/prysmaticlabs/prysm/beacon-chain --help
...
   --chain-config-file value       The path to a YAML file with chain config values
   --clear-db                      Prompt for clearing any previously stored data at the data directory (default: false)
   --config-file value             The filepath to a yaml file with flag values
```

Unfortunately I don't have a concrete idea on how to implement this using your config format, or if it's possible to add annotations to the config.

**Comment by polarker** [comment]
Multi-line comments are supported in HOCON format, not like JSON format. I could spend some time in 1-2 weeks adding some initial docs

**Comment by killerwhile** [comment]
I didn't know about the multiline comments in hocon.  Sounds great!
I don't think it's urgent, so please treat this with according priorities, but it would be good to have such description at some point in time.

**Comment by polarker** [comment]
Some initial HOCON comments for important keys have been added into `system.conf` and `network.conf`

**Comment by killerwhile** [comment]
that's awesome, thanks a lot having taking time for this one!
