### ISSUE TITLE
When I'm submitting twice the same transaction, a meaningful error message should be displayed.

### ISSUE THREAD

**Issue by killerwhile** [alephium/alephium#133]
# Issue type
improvement

# Affected version
v0.7.1

# Description
When I submit the same TX twice (same amount and recipient) in a short period of time, the second fails with a 400 (server error).
The returned error should be more meaningful, and maybe returns a 409 (conflict) or 429 (too many requests)?

**Comment by polarker** [comment]
With #166, submitting the same TX twice will create two sequential TXs without any error. I am closing this now.
