### ISSUE TITLE
Add an option to auto-start mining at startup

### ISSUE THREAD

**Issue by killerwhile** [alephium/alephium#172]
# Issue type

improvement

# Affected version

v0.7.3

# Description

Currently "start-mining" API call must be explicitly called after alephium restart.
An option to turn on auto-start mining at startup might be convenient!

**Comment by polarker** [comment]
This should be supported now, as our external CPU miner start mining automatically.

**Comment by killerwhile** [comment]
And the mining companion is starting mining, if it is configured to do so.
