### ISSUE TITLE
Why is the synchronization node so slow, it is still 1500 for one night synchronization

### ISSUE THREAD

**Issue by ZhangMing520** [alephium/alephium#181]

**Comment by polarker** [comment]
@ZhangMing520 Sorry for the late reply, we have updated our testnet in between, as some of the miners start mining before the node is synced. Please use the latest IP addresses in the Testnet Guide.

This issue will be fixed n our next release! Thank you for reporting.

**Comment by ZhangMing520** [comment]
@polarker Thanks, maybe because I started mining in advance，I try stop mining

**Comment by polarker** [comment]
I am closing this, as it's fixed here: https://github.com/alephium/alephium/pull/183

500 ALF is rewarded for the report. Many thanks
