### ISSUE TITLE
I have stop mining, and upgrade jar, use latest IP addresses， Node synchronization is still very slow

### ISSUE THREAD

**Issue by ZhangMing520** [alephium/alephium#186]
My last issue : https://github.com/alephium/alephium/issues/181

~/.alephium/user.conf
![image](https://user-images.githubusercontent.com/16587215/116276763-66c56b80-a7b7-11eb-814a-3caccabe1034.png)

this is my service 
`[Unit]
Description=Alephium Node
After=network.target

[Service]
User=root

Restart=always
RestartSec=5

WorkingDirectory=/root/alephium/
ExecStart=java -jar -Xmx4G alephium-0.7.3.jar

[Install]
WantedBy=multi-user.target
`
Beijing time (2021-04-28 00:27:00) command output
![image](https://user-images.githubusercontent.com/16587215/116277500-1d295080-a7b8-11eb-8c53-c6cbf11657ef.png)

**Comment by polarker** [comment]
You will need to clean your existing history under `~/.alephium/db-*` first, as we have launched a new testnet. Let me know if it works for you!

**Comment by ZhangMing520** [comment]
Ok, I will try it first, I will check the result in the morning, and then I will reply

**Comment by ZhangMing520** [comment]
@polarker It seems to work, because it's already 300 in just a few minutes

**Comment by polarker** [comment]
That's great! It should work, as many people have tried it lately. I will close it tomorrow if no further questions

**Comment by ZhangMing520** [comment]
Thanks , it works, the node almost finished syncing.
