### ISSUE TITLE
wallets:deriveNextAddress should return same structure than changeActiveAddress

### ISSUE THREAD

**Issue by killerwhile** [alephium/alephium#194]
# Issue type

improvement

# Affected version

v0.7.5

# Description

`/wallets/{wallet_name}/deriveNextAddress` API returns a plain string as the response. The data type looks pretty similar to `/wallets/{wallet_name}/changeActiveAddress`, so it might be interesting to align for consistency.

**Comment by tdroxler** [comment]
so you mean: `deriveNextAddress` should return : 

```
{
  "address: "T1....."
}
```
It would indeed make more sense and it's more future proof in case we want to add more info on that endpoint response later.

I'll try to tackle that soon.

**Comment by killerwhile** [comment]
yes, output to be something like you proposed: 
```
{
  "address: "T1....."
}
```
