### ISSUE TITLE
Single wallet info API call

### ISSUE THREAD

**Issue by killerwhile** [alephium/alephium#196]
# Issue type

Feature request

# Affected version

v0.7.5

# Description

A API `GET /wallets/{wallet_name}` would be useful to get details about a single wallet, such as "Is my wallet locked?"
Currently iterating through all the wallets is needed to do the same.

**Comment by tdroxler** [comment]
:+1: totally agree,  I'll do it at the same time as #194

**Comment by killerwhile** [comment]
Thanks for the PR, LGTM now!
