### ISSUE TITLE
API call to inform is the node is currently mining or not.

### ISSUE THREAD

**Issue by killerwhile** [alephium/alephium#197]
# Issue type

Feature request

# Affected version

v0.7.5

# Description

`/infos/self-clique` could be extended to return the mining status (for instance, `isMining`)

Or another, dedicated, API function would work, too.

**Comment by tdroxler** [comment]
We are thinking of adding an endpoint `infos/node` because the `isMining` info isn't linked to the clique (you could start mining only on one node of your clique) + we can imagine latter other information for that endpoint, e.g. which groups is managed by this node.

**Comment by killerwhile** [comment]
Having a dedicated endpoint for the node sounds good. Thanks
