### ISSUE TITLE
Add a ping API endpoint  to validate the connectivity from the client

### ISSUE THREAD

**Issue by killerwhile** [alephium/alephium#213]
# Issue type

Improvement

# Affected version

v0.7.7

# Description

It would be quite convenient to have a `Ping` API endpoint to ensure the client has connectivity to the server.

**Comment by polarker** [comment]
As it's a P2P network based on Kademlia protocol, each node connects to multiple nodes in the network. There is no centralized server.

Right now, you could use `/infos/inter-clique-peer-info` to get all the **current** connected peers. Will this do the work for you ?

**Comment by killerwhile** [comment]
I'm talking about clients (such as the twitter faucet) to be able to validate connectivity with the full node. Not the p2p network side of the protocol.

**Comment by polarker** [comment]
> I'm talking about clients (such as a wallet or the twitter faucet) to be able to validate connectivity with the full node. Not the p2p network side of the protocol.

I see, you want to have an API for health check. Do you think `/infos/self-clique` can serve the purpose?

I checked both BTC and ETH, none of them have a specific API for health check. BTC has a ping API for checking the delay of p2p protocol

**Comment by killerwhile** [comment]
Yes, I think `/infos/self-clique` could do it. Thanks
