### ISSUE TITLE
Improve networking API

### ISSUE THREAD

**Issue by polarker** [alephium/alephium#416]
- [ ] group all of the networking api under the same section
- [x] add an API to ban IP manually
- [x] add an API for unreachable IP
- [x] add more information for inter clique cliques: client version for example

**Comment by ferdinandhodl** [comment]
- [ ] fix API SSL connection for 0.0.0.0 not only 127.0.0.1

Setting `alephium.api.network-interface = "0.0.0.0"` in `~/.alephium/user.conf` and then trying to connect to https://IP.of.node:12973/docs/ results in error `SSL_ERROR_RX_RECORD_TOO_LONG`

**Comment by polarker** [comment]
> * [ ]  fix API SSL connection for 0.0.0.0 not only 127.0.0.1
> * [ ]  redirect from http to https in case the API is used from remote host
> 
> Setting `alephium.api.network-interface = "0.0.0.0"` in `~/.alephium/user.conf` and then trying to connect to https://IP.of.node:12973/docs/ results in error `SSL_ERROR_RX_RECORD_TOO_LONG`

Users will need to manage SSL certificates manually if we want to support https. It's going to be very painful. We decided to support `api-key` instead, which is much easier to setup.
