### ISSUE TITLE
Mining not working with the newest docker version

### ISSUE THREAD

**Issue by tappikone** [alephium/alephium#437]
I started completely from scratch and still getting
alephium_gpu_miner_1  | Will connect to broker @:10973
alephium_gpu_miner_1  | the server is connected -111 0x55ab1f33dd60
alephium_gpu_miner_1  | hashrate: 0.000000 (hash/sec)
alephium_gpu_miner_1  | error on_read -4095
alephium_gpu_miner_1  | getaddrinfo: Name or service not known
alephium_gpu_miner_1  | error on_read -4095
What broke the docker build? Running standalone gpu-miner works so it's definitely docker image issue

**Comment by polarker** [comment]
this should be resolved by this PR https://github.com/alephium/alephium/pull/439

**Comment by tappikone** [comment]
Seems to have been fixed, thanks!
