### ISSUE TITLE
Grafana dashboard cannot bind IP

### ISSUE THREAD

**Issue by BlankerL** [alephium/alephium#440]
Grafana dashboard can only be viewed from 127.0.0.1. 

I host it on a personal computer in my subnet and would like to set the Grafana dashboard reachable on a different computer, but the site could not be visited under 192.168.50.0/24.

Shall it be configurable?

**Comment by h0ngcha0** [comment]
Thanks for reporting the issue!
By default docker-compose binds the port with `0.0.0.0` address, which should make Grafana dashboard accessible from another computer. 
If you run `docker ps`, do you see Grafana port (3000) bound with IP address `0.0.0.0`? e.g.

```
75fc32b22150   grafana/grafana:7.2.1       "/run.sh"                13 minutes ago   Up 12 minutes   0.0.0.0:3000->3000/tcp
```

**Comment by BlankerL** [comment]
Thanks! I think I found the problem. The docker is in unRaid system, and the docker-composer didn't successfully launch the grafana. I have manually launched the grafana and everything works fine now.
