### ISSUE TITLE
Make API key enabled by default

### ISSUE THREAD

**Issue by polarker** [alephium/alephium#472]
If user does not provide an API key, we will generate a random one and output it in the log.

Shall we make it possible for people to disable it ? Two options:
1. add field `api-key-enabled = true`, if one wants to turn it off, one could make `api-key-enabled = false`
2. no field `api-key-enabled = true`, no such way to turn it off in this way

I prefer option 2, so it's always mandatory

**Comment by tdroxler** [comment]
ahah we used to have that auto-generated api-key on start, but it was painful for developing, I guess it's time to bring it back :)

I think we need to go with 1, for example for our desktop wallet which is calling a public node, which has to be "open". But we need to add a setting in our wallet to be able to set an API key, for people calling a local node which has an API key.

**Comment by polarker** [comment]
> ahah we used to have that auto-generated api-key on start, but it was painful for developing, I guess it's time to bring it back :)
> 
> I think we need to go with 1, for example for our desktop wallet which is calling a public node, which has to be "open". But we need to add a setting in our wallet to be able to set an API key, for people calling a local node which has an API key.

Nice catch. Indeed, we should make it able to be disabled in this case.
