### ISSUE TITLE
full nodes doesnt work on new windows update 

### ISSUE THREAD

**Issue by faikuluturk** [alephium/alephium#498]
![image](https://user-images.githubusercontent.com/86348797/149642598-2a7913fe-419d-4a66-8e0e-f712b13165b4.png)

**Comment by polarker** [comment]
> ![image](https://user-images.githubusercontent.com/86348797/149642598-2a7913fe-419d-4a66-8e0e-f712b13165b4.png)

Hi, I think this is the root cause: https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#toLowerCase() I will try to fix it as soon as possible

**Comment by polarker** [comment]
@faikuluturk please check v1.2.2, which fixed your issue
