### ISSUE TITLE
How to make the node Swagger UI listen to 0.0.0.0 instead of 127.0.0.1

### ISSUE THREAD

**Issue by rlinxy** [alephium/alephium#501]
I would like to access the Swagger UI from remote ip. Just went through the system.conf, couln't find where to set it.
Now it only listen to 127.0.0.1.
Please help, thanks.

**Comment by 42phoenix42** [comment]
@rlinxy in .alephium/user.conf
`alephium.api.network-interface = "0.0.0.0"
alephium.api.api-key = "some-long-string-for-swagger-request-auth(if you don't specify api-key other users can use your swagger ui without auth)"`

**Comment by rlinxy** [comment]
thanks
