### ISSUE TITLE
Mining with my Hiveos Rig on my Personal Node

### ISSUE THREAD

**Issue by boatnofloat** [alephium/alephium#503]
I'm looking to connect my hiveos worker to my node running on my windows machine. I've opened up the required ports to my protected network, which both machines are running on. Do the capabilities exist to complete this objective? What are the steps i must take to achieve this? Thank you.

**Comment by vakvlad2** [comment]
it would be cool to see a description for using a third-party miner connected to your own node in HiveOS

**Comment by diomark** [comment]
@boatnofloat  i'm sure you've already figured this out, but I don't think this is the right place to ask in a git issue.. If you still need help, please ask in the discord here -  https://discord.gg/mbrsZ4eE - specifically in the mining channel - https://discord.com/channels/747741246667227157/887695304453939210

**Comment by diomark** [comment]
(I'd suggest closing this issue)

**Comment by boatnofloat** [comment]
Closed
