### ISSUE TITLE
Internal server error when trying to get balance of not empty wallet

### ISSUE THREAD

**Issue by mgrom** [alephium/alephium#507]
I'm running full node on one machine (x.x.x.23), and miner on another (x.x.x.23). I've managed to run everything, miner is mining, I've already received some coins on two of four addresses. All API endpoints are working fine except those related to coins in wallet: balance, sweap etc.
When I'm trying to use balance then I got "Internal server error". 
I've checked logs of running full node and I've found this:

Exception when sending request: GET http://127.0.0.1:12973/addresses/zzzzzzzzzzzzzzzzzzzzzzzzzzz/balance (where zz is address of my wallet)
But, funny thing, when I'm on full node machine and I use curl to:
1. run the same call as from swagger - I got the same error
2. run the call from exception - I got balance of specified address

I can't even transfer coins to other wallet. Please help :)

**Comment by polarker** [comment]
This is fixed on Discord. I am closing it
