### ISSUE TITLE
Sync process crashed

### ISSUE THREAD

**Issue by PSLLSP** [alephium/alephium#517]
alephium-1.2.5.jar
Ubuntu 18.04.6

I try to sync blockchain, I started from block 0. I observed crash, node is running but it doesn't receive new blocks, no new messages in the console.

```
$ java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-8u312-b07-0ubuntu1~18.04-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)
```

I start node with command `java -jar -Xmx1G alephium-1.2.5.jar`

Crash situation:
```
2022-02-02 18:56:03,895 [-dispatcher-7] INFO  o.a.f.h.BlockChainHandler              - hash: 000000000010f59422ccd2fb3004f7a7616281f0d5ea9e451c14b91ea7b46a36; chain: 1->2; height: 94101/94101; total: 1502628; blockTime: 3303ms; #tx: 1
2022-02-02 18:56:12,563 [dispatcher-10] INFO  o.a.f.h.BlockChainHandler              - d7533c42 is validated
2022-02-02 18:56:16,900 [-dispatcher-7] INFO  o.a.f.h.BlockChainHandler              - hash: 00000000001ded68b9217d4d02d6bd66fc02afa0f81752ce42c48966d7533c42; chain: 0->2; height: 94139/94139; total: 1502629; blockTime: 111847ms; #tx: 2
Uncaught error from thread [flow-akka.actor.internal-dispatcher-741Exception in thread "AsyncHttpClient-timer-4-1" Exception in thread "vertx-blocked-thread-checker" ]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[Uncaught error from thread [flow-akka.actor.default-dispatcher-13]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[flow]
```

**Comment by polarker** [comment]
> 

Did restart help? The log said heap space issue, so it seems 1G is not enough. Maybe try `-Xmx2G` or remove `-Xmx1G`

**Comment by PSLLSP** [comment]
I try to synchronize on 2 different PCs. One node is almost synchronized, second crashed few hours ago. I restarted it and it fetches new blocks. In the case it will crash again, I will try to increase heap memory... Maybe that this crash signals rare memory leak...

**Comment by polarker** [comment]
> I try to synchronize on 2 different PCs. One node is almost synchronized, second crashed few hours ago. I restarted it and it fetches new blocks. In the case it will crash again, I will try to increase heap memory... Maybe that this crash signals rare memory leak...
> 
> I followed instructions at https://wiki.alephium.org/Full-Node-Starter-Guide.html The instructions talk about `alephium-1.2.4.jar`, older version. It doesn't work, I was able to synchronize only about 60000 blocks. Please, update your wiki...

1. I don't think 1.2.4 will have any trouble, as many community members have been running 1.2.4
2. I have updated the wiki to 1.2.5
