### ISSUE TITLE
mining address is missing character

### ISSUE THREAD

**Issue by PSLLSP** [alephium/alephium#518]
alephium-1.2.5.jar

I followed instructions https://wiki.alephium.org/Solo-Mining-Guide.html

Mining addresses has to be created, in the API. In my case, second mining address is 1 character shorter. In the real, it is the same address as in field **activeAddress**. I am not sure but it looks like an issue...

Are addresses for ALPH fixed length? In your example in documentation all four addresses have the same length... **activeAddress** is the same as 3rd address in the list.

---

It is easy to replicate, I created 10 wallets and 2 of them has this "issue". One example:

```
{
  "walletName": "TEST1-7",
  "password": "TOPsecret",
  "mnemonic": "remember strategy boost pottery dog knock wreck gas can column under time flat whisper supreme apart coyote bottom problem owner digital step organ wolf"
}
```

Created mining addresses:
```
{
  "activeAddress": "1AHxqLEaPhrmLorcaX3TQa64qyDQfBgPz7iFcPsaCUjAT",
  "addresses": [
    {
      "address": "1AHxqLEaPhrmLorcaX3TQa64qyDQfBgPz7iFcPsaCUjAT",
      "publicKey": "0243642ab32325d02ba67aea2906fc1e9b06792e9965664a1ebb31780d75cab6d4",
      "group": 0,
      "path": "m/44'/1234'/0'/0/8"
    },
    {
      "address": "14SnAKpbzhRqaMSRhY4CNn1LMRAhaBZqYfivA5FVCAP6Q",
      "publicKey": "037a089336d0a9876d6a772622ef5ef582f3625ce118e35d026a1600444fe1d846",
      "group": 1,
      "path": "m/44'/1234'/0'/0/0"
    },
    {
      "address": "1ch2RfT2zHpKcFqoosxtrUA3wA1b7ENasxPgjC1D48RP",
      "publicKey": "0323b39618e43a06f5885bf943fbdb9d5555b7f697b28936cc20072bfe11b1b261",
      "group": 2,
      "path": "m/44'/1234'/0'/0/4"
    },
    {
      "address": "14cDs7ff3GXG87EFXXhqi8P6wwv111GGCyKgwD9ZtXTWG",
      "publicKey": "03c4bceec2d83888b3235dd856920dce3ffc6bcce133c1022c0119b0f34fa32995",
      "group": 3,
      "path": "m/44'/1234'/0'/0/2"
    }
  ]
}
```

Addresses created, `1ch2RfT2zHpKcFqoosxtrUA3wA1b7ENasxPgjC1D48RP` is shorter:
```
1AHxqLEaPhrmLorcaX3TQa64qyDQfBgPz7iFcPsaCUjAT
14SnAKpbzhRqaMSRhY4CNn1LMRAhaBZqYfivA5FVCAP6Q
1ch2RfT2zHpKcFqoosxtrUA3wA1b7ENasxPgjC1D48RP
14cDs7ff3GXG87EFXXhqi8P6wwv111GGCyKgwD9ZtXTWG
```

**Comment by tdroxler** [comment]
hi @PSLLSP , yes addresses can have different length. Base58 is a bit like numbers. Since we can have 99 and 100 with 2 digits and 3 digits, same for base58.

Also if you work one day with a multisig address, you'll see that they can be much bigger, for example: https://explorer.alephium.org/#/addresses/X4QxH1pzNyqmMKHjtGhtcZi3abzAuktFnj5dLVa2Q2jCtd4sm5vqRtsED7PkyvyvNFiVgMVcP5kmyKz4m7XsfCh169c36ZezkwpDEnuQSxfQfYDhbFvLDz8BN3HErjusisymDT
