### ISSUE TITLE
checksum is confusing as it's sha256 and not md5sum

### ISSUE THREAD

**Issue by diomark** [alephium/alephium#548]
The release notes should mention that the checksum is a sha256sum - had a user on discord claim that the checksum file  alephium-1.3.2.jar.checksum didn't match, and it doesn't match a md5sum which is the most common checksum I've seen on files.. but it's correctly matching the sha256sum for that file.

i.e. please clarify in the release notes that the checksum file is a sha256sum checksum.

**Comment by polarker** [comment]
> The release notes should mention that the checksum is a sha256sum - had a user on discord claim that the checksum file alephium-1.3.2.jar.checksum didn't match, and it doesn't match a md5sum which is the most common checksum I've seen on files.. but it's correctly matching the sha256sum for that file.
> 
> i.e. please clarify in the release notes that the checksum file is a sha256sum checksum.

Thanks for reporting. I am considering to rename the file as `alephium-x.x.x.jar.sha256sum`. HDYT?

**Comment by diomark** [comment]
sounds good. but actually, I don't know of a native way in windows to get a sha256sum - might be good to include md5sum checksum in addition?

**Comment by polarker** [comment]
md5sum is considered as insecure nowadays. For sha256sum on windows, this command should help: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-filehash?view=powershell-7.2

**Comment by diomark** [comment]
I can confirm that the powershell works -

![image](https://user-images.githubusercontent.com/20622085/161402947-acf32695-d5f1-4ba7-a45d-860492b0d85b.png)

So yes, simply renaming the checksum file to .sha256sum would be a good solution here..

**Comment by polarker** [comment]
> I can confirm that the powershell works -
> 
> ![image](https://user-images.githubusercontent.com/20622085/161402947-acf32695-d5f1-4ba7-a45d-860492b0d85b.png)
> 
> So yes, simply renaming the checksum file to .sha256sum would be a good solution here..

I just renamed them as `.sha256.checksum` instead of `.sha256sum` due to restrictions of Github. I will update the CI to use the same naming from the next release.

**Comment by diomark** [comment]
Thanks for the quick action.
