### ISSUE TITLE
Return gas amount and price when sending request to /contracts/unsigned-tx/build-contract

### ISSUE THREAD

**Issue by lf94** [alephium/alephium#555]
The current behavior is no gas amount or price is returned when sending a request to this endpoint. It means the developer must specify their own gas values. This differs from the /transactions/build endpoint which do return gas values.

This may be the case because contracts are less trivial to calculate gas for, so the feature was deferred.

Currently dapps (voting-demo) specify their own gas, but this is not good for malicious dapps which request an exorbitant amount of gas and proceed to burn gas for no good reason. Less advanced users will be caught off guard.

**Comment by lf94** [comment]
/contracts/unsigned-tx/build-script needs the same treatment

**Comment by nop33** [comment]
Is there an update on this? I cannot really test the desktp wallet walletconnect PR https://github.com/alephium/desktop-wallet/pull/204, I keep getting the error:

```
"Failed in validating tx 98cbef9e1b6ec812df6ba15d87dc4f4f762e677f5bc58b404642f944d4e4b039 due to InvalidStartGas: 0001010101010000000715000a684bf981f41cd46c06e88f2642caeac112b95a2c458189c217aece8c55f71813c1e8d4a51000a21440870703402e4064407f010100000019a004041c4d5a0d2b59a005454da005a00613c22d79883d2000a7a006b10dab0ca1010ca10203a10401010202001da004031ca003041c1a4d1601a00513c22d79883d2000a71601b10dac1600031c4c05a0010d2aa1014a04a0020d2aa102010000000011a004031ca003041c1a4d5a0d2b59a005454d03a1031440600703114973206974206120676f6f64206461793f020002000000000004000a684bf981f41cd46c06e88f2642caeac112b95a2c458189c217aece8c55f71804000a684bf981f41cd46c06e88f2642caeac112b95a2c458189c217aece8c55f7180dae805b8d80c1174876e800014586978b994b645b18a55219d84a0a6cdc675cd7be3cf749bc367e7ab67b7dd0c8d7143c00033123981646bd73d1354b6e4cf9ea44794ebe6ddc7457a59e181cb9fdc207adee0001a51c4b8ed88d9b568c83eb263751d6a8fda590a38fb915012817b4b377b375bf2e3b380385a24f46f7f4253adc13da160594f5e7a219cc3523b077d6519939d800"
```

**Comment by polarker** [comment]
@nop33 How did you set the gas?

**Comment by nop33** [comment]
If you mean what values I used to call the `postContractsUnsignedTxBuildContract` endpoint, these are the ones:
```
gas: 6000000
gasPrice: "100000000000"
```

**Comment by polarker** [comment]
> If you mean what values I used to call the `postContractsUnsignedTxBuildContract` endpoint, these are the ones:
> 
> ```
> gas: 6000000
> gasPrice: "100000000000"
> ```

You could just leave both `undefined`, then full node will estimate the right amount
